### ISSUE TITLE
drush vnew fails if id_rsa.pub does not exist

### ISSUE THREAD

**Issue by mattcoker** [GetValkyrie/valkyrie#56] opened 2015-04-09 03:08 UTC
On my computer, I had a very fresh install of OS X and had run short-stack recently. Apparently, I did not even have a `~/.ssh` directory, much less any files inside of it. I'm not sure if this issue would occur if the `~/.ssh` directory existed, but the id_rsa.pub file did not.

```
➜  Drupal  drush vnew valkyrie
Valkyrie project initialized at: valkyrie                                                                                 [ok]
Bringing machine 'valkyrie' up with 'virtualbox' provider...
==> valkyrie: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    valkyrie: Box Provider: virtualbox
    valkyrie: Box Version: >= 0
==> valkyrie: Loading metadata for box 'ubuntu/trusty64'
    valkyrie: URL: https://atlas.hashicorp.com/ubuntu/trusty64
==> valkyrie: Adding box 'ubuntu/trusty64' (v14.04) for provider: virtualbox
    valkyrie: Downloading: https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box
==> valkyrie: Successfully added box 'ubuntu/trusty64' (v14.04) for 'virtualbox'!
There are errors in the configuration of this machine. Please fix
the following errors and try again:

File provisioner:
* File upload source file /Users/mattcoker/.ssh/id_rsa.pub must exist
```

**Comment by mattcoker** [comment] 2015-04-09 03:09
Immediately after the above, I ran `ssh-keygen -t rsa`, removed the existing valkyrie directory, and ran a vnew. Worked fine at that point.

**Comment by ergonlogic** [comment] 2015-04-13 17:25
Duplicate of #43

**Closed as completed by ergonlogic** 2015-04-13 17:25 UTC
