### ISSUE TITLE
drush vnew valkyrie Ubuntu Trusty host

### ISSUE THREAD

**Issue by niccolox** [GetValkyrie/valkyrie#28] opened 2015-03-10 05:46 UTC
nice cluster of errors
drush vnew valkyrie
....
valkyrie: Running provisioner: file...
Failed to upload a file to the guest VM via SCP due to a permissions
error. This is normally because the SSH user doesn't have permission
to write to the destination location. Alternately, the user running
Vagrant on the host machine may not have permission to read the file.

Source: /home/niccolox/.bashrc
Dest: /home/vagrant/.bashrc
The external command could not be executed due to an application     [error]
error.
Illegal string offset 'site' backend.inc:1030                        [warning]
The command could not be executed successfully (returned: ssh: Could [error]
not resolve hostname valkyrie.local: Name or service not known

**Comment by ergonlogic** [comment] 2015-03-12 15:00
I believe this is a duplicate of several other issues that should mostly be resolved. Please post a new issue with more specific errors, as you encounter them.

Also, thanks for your bravery at being an early tester/adopter :)

**Closed as completed by ergonlogic** 2015-03-12 15:00 UTC

**Comment by niccolox** [comment] 2015-03-15 00:51
works now.
