### ISSUE TITLE
Unable to Install Valkyrie

### ISSUE THREAD

**Issue by cookiedoode** [GetValkyrie/valkyrie#73] opened 2015-08-14 18:25 UTC
Towards the end of the valkyrie install, the following error appears:

The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using.

This also prevents creation of valkyrie virtual box as well.

**Comment by ergonlogic** [comment] 2015-08-14 18:44
So this is the result of running `drush vnew`?

**Comment by cookiedoode** [comment] 2015-08-14 18:57
Yes, this occurs right before Ansible attempts to start building

**Comment by ergonlogic** [comment] 2015-08-14 18:59
Can you describe your environment? What OS, version of VirtualBox, Vagrant, etc.

**Comment by cookiedoode** [comment] 2015-08-14 19:01
OSX Yosemite 10.10.4
Virtual Box 4.3.28
vagrant-dns (0.6.0)
- Version Constraint: 0.6.0
  vagrant-share (1.1.4, system)
  vagrant-triggers (0.5.0)
- Version Constraint: 0.5.0

**Comment by ergonlogic** [comment] 2015-08-14 19:03
It may be an intermittent issue. Have you tried building the project again? Within the existing project, you can run `vagrant destroy -f && vagrant up`.

**Comment by cookiedoode** [comment] 2015-08-14 19:07
I have followed your instruction, but am still getting the same error.  I have removed valkyrie, destroyed it, and reinstalled it and it gives me the same error

**Comment by ergonlogic** [comment] 2015-08-14 19:08
Can you launch a default Vagrant VM? Just `mkdir test; cd test; vagrant init; vagrant up`

**Comment by cookiedoode** [comment] 2015-08-14 19:11
It failed as well..  Please see the screenshot below

<img width="565" alt="screen shot 2015-08-14 at 2 10 04 pm" src="https://cloud.githubusercontent.com/assets/12419148/9281907/3b7f0056-428e-11e5-9738-e4a21410a628.png">

**Comment by ergonlogic** [comment] 2015-08-14 19:13
Valkyrie depends on a working Vagrant install. It looks like a network error. Perhaps check your firewall settings. That said, I'm going to close this issue, since it clearly isn't a problem with Valkyrie. I'd suggest that you search the Vagrant issue queues, and open a support request there if you can't find an existing solution.

**Comment by cookiedoode** [comment] 2015-08-14 19:17
Thank you for your help!

**Comment by cookiedoode** [comment] 2015-08-14 22:23
Just wanted to give an update. @MatthewHager's computer installed valkyrie without any problem.  He matched the versions on my computer and came across the same errors as mine.  The versions are as follows:

Virtual Box: 4.3.30
Vagrant: 1.7.4
vagrant-dns (0.6.0)
vagrant-share (1.1.4, system)
vagrant-triggers (0.5.1)

I'm going to try to roll back versions to see if any adjustment fixes the problem

**Comment by MatthewHager** [comment] 2015-08-15 01:11
Can confirm this is an issue if you use the latest 4.x Vbox with the latest plugins and vagrant.

**Comment by RealLukeMartin** [comment] 2015-08-16 02:33
For comparison, my versions are set to these with `drush vnew` working smooth and stable:

```
Virtualbox 4.3.28
vagrant 1.7.2
vagrant-dns (0.6.0)
vagrant-share (1.1.3, system)
vagrant-triggers (0.5.0)
```

**Comment by ergonlogic** [comment] 2015-08-16 04:22
Both Vagrant and VirtualBox differ here. We need to narrow down, and find
the root cause.

FWIW, the working versions of both Vagrant
http://www.vagrantup.com/download-archive/v1.7.2.html and Vbox
http://download.virtualbox.org/virtualbox/4.3.28/ remain available.

Also, please post the entire error log (to a gist, ideally). I assume the
issue is with one of the Valkyrie faux-plugins. Their log output will
hopefully help pinpoint the code that needs re-factoring.

**Closed as completed** 2015-08-17 04:13 UTC
